<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('products')->insert([
            [
                'product_name' => 'GTX 4080',
                'product_model' => 'RTX4080-X',
                'product_part' => 'GPU',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 1200,
                'product_description'=> 'NVIDIA graphics card with ultra-fast ray tracing for high-end gaming.',
                'product_createdate' => now(),
                'product_stock' => 15, // Added default stock
                'product_image' => 'https://pchocasi.com.tr/wp-content/uploads/2022/09/Nvidia-GeForce-RTX-4080-1.jpg'
            ],
            [
                'product_name' => 'Intel i9 14900K',
                'product_model' => 'i9-14900K',
                'product_part' => 'CPU',
                'product_colour' => 'Silver',
                'category_id' => 1,
                'product_price' => 700,
                'product_description'=> 'Powerful 14th Gen Intel CPU, perfect for all workloads.',
                'product_createdate' => now(),
                'product_stock' => 10,
                'product_image' =>'https://media.very.co.uk/i/very/W1HGC_SQ1_0000000099_N_A_SLf?$pdp_576x768_x2$&fmt=webp'
            ],
            [
                'product_name' => 'AMD Ryzen 9 7950X',
                'product_model' => 'Ryzen9-7950X',
                'product_part' => 'CPU',
                'product_colour' => 'Silver',
                'category_id' => 1,
                'product_price' => 650,
                'product_description'=> 'Top-tier AMD processor delivering multi-core performance for gaming.',
                'product_createdate' =>now(),
                'product_stock' => 4,
                'product_image' =>'https://m.media-amazon.com/images/I/5116zdA9uyL._AC_SL1200_.jpg'
            ],
            [
                'product_name' => 'Corsair 32GB DDR5 RAM',
                'product_model' => 'Vengeance DDR5-32GB',
                'product_part' => 'RAM',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 150,
                'product_description'=> 'High-speed DDR5 memory kit to maximize system performance and smooth multitasking.',
                'product_createdate' =>now(),
                'product_stock' => 12,
                'product_image' => 'https://m.media-amazon.com/images/I/61eNiRqRcXL._AC_UF894,1000_QL80_.jpg'
            ],
            [
                'product_name' => 'Samsung 2TB NVMe SSD',
                'product_model' => '970 Evo Plus',
                'product_part' => 'SSD',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 250,
                'product_description'=> 'Ultra-fast NVMe SSD with lightning-fast boot times and application loading.',
                'product_createdate' =>now(),
                'product_stock' => 17,
                'product_image' =>'https://m.media-amazon.com/images/I/71ByVZ1x2vL.jpg'
            ],
            [
                'product_name' => 'ASUS ROG Motherboard',
                'product_model' => 'ROG Strix Z790',
                'product_part' => 'Motherboard',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 400,
                'product_description'=> 'Feature-rich motherboard with high-end gaming features.',
                'product_createdate' =>now(),
                'product_stock' => 10,
                'product_image' =>'https://dlcdnwebimgs.asus.com/files/media/B51D103D-2941-412E-8479-AF994957093B/v1/img/kv/ROG-Strix-X670E-E-Gaming.png'
            ],
            [
                'product_name' => 'Cooler Master 750W PSU',
                'product_model' => 'V750 Gold',
                'product_part' => 'PSU',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 120,
                'product_description'=> 'Reliable and efficient power supply with enough wattage to handle needy components.',
                'product_createdate' =>now(),
                'product_stock' => 2,
                'product_image' =>'https://m.media-amazon.com/images/I/91bdi5kqQGL._AC_UF1000,1000_QL80_.jpg'
            ],
            [
                'product_name' => 'Noctua CPU Cooler',
                'product_model' => 'NH-D15',
                'product_part' => 'Cooling Fan',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 100,
                'product_description'=> 'Premium air cooler for efficient heat management.',
                'product_createdate' =>now(),
                'product_stock' => 0,
                'product_image' =>'https://img.overclockers.co.uk/images/HS-03M-NC/05e4e38b81d0351597f55b71637a424c.jpg'
            ],
            [
                'product_name' => 'NZXT H710 Case',
                'product_model' => 'H710 Matte Black',
                'product_part' => 'PC case',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 200,
                'product_description'=> 'Well-ventilated and well-built PC case with sleek design.',
                'product_createdate' =>now(),
                'product_stock' => 13,
                'product_image' =>'https://nzxt.com/cdn/shop/files/h7-emea-hero-2000x2000.png?v=1762528364.'
            ],
            [
                'product_name' => 'Corsair 2x120mm Case Fans',
                'product_model' => 'AF120',
                'category_id' => 1,
                'product_part' => 'Cooling Fan',
                'product_colour' => 'Black',
                'product_price' => 50,
                'product_description'=> 'High-performance case fans to keep your system cool under load.',
                'product_createdate' =>now(),
                'product_stock' => 10,
                'product_image' =>'https://m.media-amazon.com/images/I/71Pgp9awWGL.jpg'
            ],
            [
                'product_name' => 'Intel Wi-Fi 6 Card',
                'product_model' => 'AX200',
                'category_id' => 1,
                'product_part' => 'NIC',
                'product_colour' => 'White',
                'product_price' => 40,
                'product_description'=> 'Next-generation Wi-Fi 6 network card for faster wireless connectivity.',
                'product_createdate' =>now(),
                'product_stock' => 4,
                'product_image' =>'https://m.media-amazon.com/images/I/71Hu6-rhsLL.jpg'
            ],
            [
                'product_name' => 'Samsung 27" Curved Monitor',
                'product_model' => 'Odyssey G5',
                'category_id' => 1,
                'product_price' => 300,
                'product_part' => 'NIC',
                'product_colour' => 'Black',
                'product_description'=> 'A curved display with vibrant colors and smooth refresh for gaming and productivity.',
                'product_createdate' =>now(),
                'product_stock' => 8,
                'product_image' =>'https://m.media-amazon.com/images/I/61VO4NO1vHL._AC_UF1000,1000_QL80_.jpg'
            ],

            [
                'product_name' => 'HyperX Gaming Rig',
                'product_model' => 'HX-5000',
                'product_part' => 'N/A',
                'product_colour' => 'Blue',
                'category_id' => 2,
                'product_price' => 1500,
                'product_description' => 'High-end gaming PC with RTX 4070 and Intel i7 processor.',
                'product_createdate' => now(),
                'product_stock' => 9,
                'product_image' => 'https://m.media-amazon.com/images/I/91QNSIAZLKL._AC_UL480_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Nova Workstation',
                'product_model' => 'NV-3000',
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'category_id' => 2,
                'product_price' => 1300,
                'product_description' => 'Reliable PC for creators and multitasking with AMD Ryzen 9.',
                'product_createdate' => now(),
                'product_stock' => 3,
                'product_image' => 'https://m.media-amazon.com/images/I/81KnlVQl3bL._AC_SY300_SX300_QL70_ML2_.jpg',
            ],
            [
                'product_name' => 'Stealth Mini-PC',
                'product_model' => 'ST-100',
                'category_id' => 2,
                'product_part' => 'N/A',
                'product_colour' => 'Green',
                'product_price' => 1000,
                'product_description' => 'Compact gaming PC with GTX 1660 Ti, perfect for small spaces.',
                'product_createdate' => now(),
                'product_stock' => 7,
                'product_image' => 'https://m.media-amazon.com/images/I/81VPFlY3WmL._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Titan Pro Gaming',
                'product_model' => 'TP-700',
                'category_id' => 2,
                'product_price' => 1800,
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'product_description' => 'Top-tier gaming experience with RTX 4080 and 32GB RAM.',
                'product_createdate' => now(),
                'product_stock' => 4,
                'product_image' => 'https://m.media-amazon.com/images/I/71JjWbIHvIL._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Eco Budget PC',
                'product_model' => 'EB-250',
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'category_id' => 2,
                'product_price' => 700,
                'product_description' => 'Affordable PC for everyday use with integrated graphics.',
                'product_createdate' => now(),
                'product_stock' => 10,
                'product_image' => 'https://m.media-amazon.com/images/I/71uQil+zxJL._AC_UY327_FMwebp_QL65_.jpg',
            ],

            [
                'product_name' => 'Ultimate Gaming Bundle',
                'product_model' => 'BrandX',
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'category_id' => 3,
                'product_part' => 'N/A',
                'product_colour' => 'Black',
                'product_price' => 2500,
                'product_description' => 'PC + monitor + keyboard + mouse combo for gamers.',
                'product_createdate' => now(),
                'product_stock' => 10,
                'product_image' => 'https://m.media-amazon.com/images/I/81EFH6sT5CL._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Creator’s Bundle',
                'product_model' => 'BrandY',
                'product_part' => 'N/A',
                'product_colour' => 'Blue',
                'category_id' => 3,
                'product_price' => 2200,
                'product_description' => 'Workstation PC bundle with dual monitors and professional accessories.',
                'product_createdate' => now(),
                'product_stock' => 6,
                'product_image' => 'https://m.media-amazon.com/images/I/613+s9cGm5L._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Mini Office Bundle',
                'product_model' => 'BrandZ',
                'category_id' => 3,
                'product_part' => 'N/A',
                'product_colour' => 'Black',
                'product_price' => 1200,
                'product_description' => 'Compact PC bundle with monitor, keyboard, and mouse for home office.',
                'product_createdate' => now(),
                'product_stock' => 9,
                'product_image' => 'https://m.media-amazon.com/images/I/61Owitvq44L._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Streaming Bundle',
                'product_model' => 'StreamMaster',
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'category_id' => 3,
                'product_price' => 1900,
                'product_description' => 'PC with webcam, mic, and capture card for live streaming setup.',
                'product_createdate' => now(),
                'product_stock' => 12,
                'product_image' => 'https://m.media-amazon.com/images/I/71uITD7P8QL._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Beginner Gamer Bundle',
                'product_model' => 'StartUp',
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'category_id' => 3,
                'product_price' => 1000,
                'product_description' => 'Entry-level gaming PC bundle with essential peripherals.',
                'product_createdate' => now(),
                'product_stock' => 2,
                'product_image' => 'https://m.media-amazon.com/images/I/712zBD3Mj-L._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'RTX 4070 Super',
                'product_model' => 'RTX4070S',
                'product_part' => 'GPU',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 650,
                'product_description'=> 'High-performance GPU ideal for 1440p gaming.',
                'product_createdate' => now(),
                'product_stock' => 10,
                'product_image' => 'https://cdn.wccftech.com/wp-content/uploads/2023/12/ASUS-NVIDIA-GeForce-RTX-4070-SUPER-12-GB-GPU-Dual-Graphics-Card.jpg'
            ],
            [
                'product_name' => 'RX 7900 XT',
                'product_model' => 'RX7900XT',
                'product_part' => 'GPU',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 720,
                'product_description'=> 'AMD flagship GPU for ultra gaming.',
                'product_createdate' => now(),
                'product_stock' => 6,
                'product_image' => 'https://www.techpowerup.com/img/6BN8YnL95l0iNZy1.jpg'
            ],
            [
                'product_name' => 'RTX 4060',
                'product_model' => 'RTX4060',
                'product_part' => 'GPU',
                'product_colour' => 'White',
                'category_id' => 1,
                'product_price' => 350,
                'product_description'=> 'Great budget gaming GPU.',
                'product_createdate' => now(),
                'product_stock' => 14,
                'product_image' => 'https://m.media-amazon.com/images/I/719gNHUGR7L._AC_SL1500_.jpg'
            ],
            [
                'product_name'=>'Ryzen 7 7800X3D',
                'product_model'=>'7800X3D',
                'product_part'=>'CPU',
                'product_colour'=>'Silver',
                'category_id'=>1,
                'product_price'=>450,
                'product_description'=>'Top gaming CPU with 3D cache.',
                'product_createdate'=>now(),
                'product_stock'=>8,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/f0e0e59d75066ec825667b71c31e3c83.256p.jpg'
            ],
            [
                'product_name'=>'Intel i7 14700K',
                'product_model'=>'i7-14700K',
                'product_part'=>'CPU',
                'product_colour'=>'Silver',
                'category_id'=>1,
                'product_price'=>420,
                'product_description'=>'High-end Intel CPU for multitasking.',
                'product_createdate'=>now(),
                'product_stock'=>9,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/c3e5d01cec2fa20b6f47fe8a400c08d6.256p.jpg'
            ],
            [
                'product_name'=>'Ryzen 5 7600X',
                'product_model'=>'7600X',
                'product_part'=>'CPU',
                'product_colour'=>'Silver',
                'category_id'=>1,
                'product_price'=>260,
                'product_description'=>'Excellent mid-range CPU.',
                'product_createdate'=>now(),
                'product_stock'=>11,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/fd6305088c9d16d59017b380fb9c408a.256p.jpg'
            ],

            [
                'product_name'=>'Kingston Fury 16GB DDR5',
                'product_model'=>'KF16',
                'product_part'=>'RAM',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>90,
                'product_description'=>'Fast DDR5 RAM kit.',
                'product_createdate'=>now(),
                'product_stock'=>20,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/547d30a3ba49dc763a8c23b28f7ac74b.256p.jpg'
            ],
            [
                'product_name'=>'G.Skill Trident Z 32GB',
                'product_model'=>'TZ32',
                'product_part'=>'RAM',
                'product_colour'=>'RGB',
                'category_id'=>1,
                'product_price'=>180,
                'product_description'=>'RGB high-performance RAM.',
                'product_createdate'=>now(),
                'product_stock'=>7,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/67c83cfd051636aaa95e8b00b6e95d6e.256p.jpg'
            ],
            [
                'product_name'=>'Corsair LPX 16GB DDR4',
                'product_model'=>'LPX16',
                'product_part'=>'RAM',
                'product_colour'=>'White',
                'category_id'=>1,
                'product_price'=>65,
                'product_description'=>'Reliable DDR4 memory.',
                'product_createdate'=>now(),
                'product_stock'=>18,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/e4bd808b09151a16fbdec0dbf447373a.256p.jpg'
            ],

            [
                'product_name'=>'WD Black SN850X 2TB',
                'product_model'=>'SN850X',
                'product_part'=>'SSD',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>220,
                'product_description'=>'High-speed NVMe SSD.',
                'product_createdate'=>now(),
                'product_stock'=>9,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/8e6dbae8a0f3c6572216c8758ce5a0b5.256p.jpg'
            ],
            [
                'product_name'=>'Crucial P5 Plus 1TB',
                'product_model'=>'P5P',
                'product_part'=>'SSD',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>110,
                'product_description'=>'Fast Gen4 SSD.',
                'product_createdate'=>now(),
                'product_stock'=>13,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/8e6dbae8a0f3c6572216c8758ce5a0b5.256p.jpg'
            ],
            [
                'product_name'=>'Samsung 990 Pro 1TB',
                'product_model'=>'990Pro',
                'product_part'=>'SSD',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>140,
                'product_description'=>'Premium SSD performance.',
                'product_createdate'=>now(),
                'product_stock'=>10,
                'product_image'=>'https://m.media-amazon.com/images/I/41IWzc1mUwL.jpg'
            ],

            [
                'product_name'=>'Corsair RM850x',
                'product_model'=>'RM850x',
                'product_part'=>'PSU',
                'product_colour'=>'White',
                'category_id'=>1,
                'product_price'=>150,
                'product_description'=>'Reliable 850W PSU.',
                'product_createdate'=>now(),
                'product_stock'=>6,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/1752baa3ddb162df098cf33b0b6eeae3.256p.jpg'
            ],
            [
                'product_name'=>'EVGA 750 G6',
                'product_model'=>'750G6',
                'product_part'=>'PSU',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>130,
                'product_description'=>'Efficient modular PSU.',
                'product_createdate'=>now(),
                'product_stock'=>7,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/98319aee12de75fdef0a2b74b918ddf5.256p.jpg'
            ],
            [
                'product_name'=>'Seasonic Focus 650W',
                'product_model'=>'Focus650',
                'product_part'=>'PSU',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>100,
                'product_description'=>'Quiet gold-rated PSU.',
                'product_createdate'=>now(),
                'product_stock'=>12,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/332544e0e8da6848b9fa83947101de60.256p.jpg'
            ],
            [
                'product_name' => 'MSI B650 Gaming Plus',
                'product_model' => 'B650-GP',
                'product_part' => 'Motherboard',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 180,
                'product_description'=> 'AM5 motherboard with PCIe 4.0 and WiFi support.',
                'product_createdate'=>now(),
                'product_stock'=>8,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/ff33ebb87ed9f5fa5f9c54d6d316ae82.256p.jpg'
            ],
            [
                'product_name' => 'ASUS Prime Z790-P',
                'product_model' => 'Z790-P',
                'product_part' => 'Motherboard',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 210,
                'product_description'=> 'Intel LGA1700 board with DDR5 support.',
                'product_createdate'=>now(),
                'product_stock'=>6,
                'product_image'=>'https://m.media-amazon.com/images/I/81Yy8CPeVEL._AC_SX679_.jpg'
            ],
            [
                'product_name'=>'Lian Li Lancool 216',
                'product_model'=>'LANCOOL 216RC-X',
                'product_part'=>'PC Case',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>95,
                'product_description'=>'High airflow case with tempered glass.',
                'product_createdate'=>now(),
                'product_stock'=>10,
                'product_image'=>'https://m.media-amazon.com/images/I/41X6Ocd7P5L.jpg'
            ],
            [
                'product_name'=>'Fractal Design Pop Air',
                'product_model'=>'PopAir',
                'product_part'=>'PC Case',
                'product_colour'=>'White',
                'category_id'=>1,
                'product_price'=>90,
                'product_description'=>'Clean design with great airflow.',
                'product_createdate'=>now(),
                'product_stock'=>9,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/048e9d2f829061df55885fb8eabd5952.256p.jpg'
            ],
            [
                'product_name'=>'Windows 11 Home',
                'product_model'=>'Win11-H',
                'product_part'=>'Operating System',
                'product_colour'=>'N/A',
                'category_id'=>1,
                'product_price'=>120,
                'product_description'=>'Windows 11 Home license key.',
                'product_createdate'=>now(),
                'product_stock'=>50,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/ed2349ecd618439a2aa96364e9445138.256p.jpg'
            ],
            [
                'product_name'=>'Windows 11 Pro',
                'product_model'=>'Win11-P',
                'product_part'=>'Operating System',
                'product_colour'=>'N/A',
                'category_id'=>1,
                'product_price'=>180,
                'product_description'=>'Windows 11 Pro license.',
                'product_createdate'=>now(),
                'product_stock'=>40,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/78f43eb1b5266ea1ad87edc95cb23ba1.256p.jpg'
            ],
            [
                'product_name'=>'Ubuntu Linux Mint USB',
                'product_model'=>'LINUX MINT 20.1',
                'product_part'=>'Operating System',
                'product_colour'=>'N/A',
                'category_id'=>1,
                'product_price'=>1000,
                'product_description'=>'Bootable Ubuntu installer USB.',
                'product_createdate'=>now(),
                'product_stock'=>4,
                'product_image'=>'https://m.media-amazon.com/images/I/61MY8X-U9ZL._AC_SY300_SX300_QL70_ML2_.jpg'
            ],
            [
                'product_name'=>'ArchNode X1 OLED',
                'product_model'=>'ARCH-USB-64GB',
                'product_part'=>'Operating System',
                'product_colour'=>'N/A',
                'category_id'=>1,
                'product_price'=>10,
                'product_description'=>'Bootable ArchLinux installer USB with a progress display.',
                'product_createdate'=>now(),
                'product_stock'=>25,
                'product_image'=>'https://github.com/Samdoses/CS2TP-Group-Project/blob/main/public/images/archusb.png'
            ]
        ]);
    }
}
