<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('products')->insert([
            [
                'product_name' => 'GTX 4080',
                'product_model' => 'RTX4080-X',
                'product_part' => 'GPU',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 1200,
                'product_tagline'=> 'NVIDIA graphics card with ultra-fast ray tracing for high-end gaming.',
                'product_description' => 'Supercharge your PC with the NVIDIA® GeForce RTX™ 4080 SUPER and RTX 4080. Bring your games and creative projects to life with accelerated ray tracing and AI-powered graphics. They\'re powered by the ultra-efficient NVIDIA Ada Lovelace architecture and 16GB of super-fast G6X memory.',
                'product_createdate' => now(),
                'product_stock' => 15, // Added default stock
                'product_image' => 'https://pchocasi.com.tr/wp-content/uploads/2022/09/Nvidia-GeForce-RTX-4080-1.jpg'
            ],
            [
                'product_name' => 'Intel i9 14900K',
                'product_model' => 'i9-14900K',
                'product_part' => 'CPU',
                'product_colour' => 'Silver',
                'category_id' => 1,
                'product_price' => 700,
                'product_tagline'=> 'Powerful 14th Gen Intel CPU, perfect for all workloads.',
                'product_description' => 'The unlocked Intel Core i9 desktop processors (14th generation) are optimised for enthusiast gamers and serious creators and help deliver high performance. Featuring Intel Thermal Velocity Boost, Intel Turbo Boost Max Technology 3.0, and support for PCIe 5.0 & 4.0, as well as DDR5 and DDR4 support. Compatible with Intel 700 Series and Intel 600 Series Chipset based motherboards.',
                'product_createdate' => now(),
                'product_stock' => 10,
                'product_image' =>'https://media.very.co.uk/i/very/W1HGC_SQ1_0000000099_N_A_SLf?$pdp_576x768_x2$&fmt=webp'
            ],
            [
                'product_name' => 'Ryzen 9 7950X',
                'product_model' => 'Ryzen9-7950X',
                'product_part' => 'CPU',
                'product_colour' => 'Silver',
                'category_id' => 1,
                'product_price' => 650,
                'product_tagline'=> 'Top-tier AMD processor delivering multi-core performance for gaming.',
                'product_description' =>
                'This Ryzen 9 chip is made for the professionals - whether it\'s gaming, creativity or productivity, this processor\'s got the power to support you.
                It\'s packed with 16 cores and it can boost up to 5.7 GHz, so it\'ll tear through intensive workflows.
                It\'s loaded with 144 MB of 2nd gen AMD 3D V-Cache for incredibly fast performance.
                It\'s 9000 series processors are built on the new Zen 5 architecture.',
                'product_createdate' =>now(),
                'product_stock' => 4,
                'product_image' =>'https://m.media-amazon.com/images/I/5116zdA9uyL._AC_SL1200_.jpg'
            ],
            [
                'product_name' => 'Corsair 32GB DDR5 RAM',
                'product_model' => 'Vengeance DDR5-32GB',
                'product_part' => 'RAM',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 150,
                'product_tagline'=> 'High-speed DDR5 memory kit to improve system performance.',
                'product_description'=> 'CORSAIR VENGEANCE RGB DDR5 memory delivers DDR5 performance, higher frequencies, and greater capacities optimized for Intel® motherboards while lighting up your PC with dynamic, individually addressable ten-zone RGB lighting.',
                'product_createdate' =>now(),
                'product_stock' => 12,
                'product_image' => 'https://m.media-amazon.com/images/I/61eNiRqRcXL._AC_UF894,1000_QL80_.jpg'
            ],
            [
                'product_name' => 'Samsung 2TB NVMe SSD',
                'product_model' => '970 Evo Plus',
                'product_part' => 'SSD',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 250,
                'product_tagline'=> 'Ultra-fast NVMe SSD with quick boot times and application loading.',
                'product_description'=> 'Upgrade everyday performance and blast through tasks faster. 990 EVO Plus with the latest NAND offers boosted sequential read/write speeds up to 7,250/6,300MB/s. Huge files, instant transfer.',
                'product_createdate' =>now(),
                'product_stock' => 17,
                'product_image' =>'https://m.media-amazon.com/images/I/71ByVZ1x2vL.jpg'
            ],
            [
                'product_name' => 'ASUS ROG Motherboard',
                'product_model' => 'ROG Strix Z790',
                'product_part' => 'Motherboard',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 400,
                'product_tagline'=> 'Feature-rich motherboard with high-end gaming features.',
                'product_description'=> 'Designed to be efficient, with 12+2 phases of power, ProCool connectors, alloy coils and durable capacitors provides stable and secure current delivery. Intel 2.5Gbps LAN port and WiFi 6E (802.11ax) provide fast, reliable connectivity for smooth, lag-free gameplay',
                'product_createdate' =>now(),
                'product_stock' => 10,
                'product_image' =>'https://dlcdnwebimgs.asus.com/files/media/B51D103D-2941-412E-8479-AF994957093B/v1/img/kv/ROG-Strix-X670E-E-Gaming.png'
            ],
            [
                'product_name' => 'Cooler Master 750W PSU',
                'product_model' => 'V750 Gold',
                'product_part' => 'PSU',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 120,
                'product_tagline'=> 'Reliable power supply with enough wattage to handle needy components.',
                'product_description'=> 'Cooler Master presents the V750 Gold PSU, with 80 PLUS Gold Efficiency, High-quality Japanese capacitors, 140mm Silent Fan, High Temperature Resilience, Fully Modular Cabling and a 10 Year Warranty',
                'product_createdate' =>now(),
                'product_stock' => 2,
                'product_image' =>'https://m.media-amazon.com/images/I/91bdi5kqQGL._AC_UF1000,1000_QL80_.jpg'
            ],
            [
                'product_name' => 'Noctua CPU Cooler',
                'product_model' => 'NH-D15 G2',
                'product_part' => 'Cooling Fan',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 100,
                'product_tagline'=> 'Premium air cooler for efficient heat management.',
                'product_description'=> 'Further improved second generation of the iconic, award-winning NH-D15: Even better quiet cooling performance thanks to 8 heatpipes, 20% more surface area and novel NF-A14x25r G2 fans!',
                'product_createdate' =>now(),
                'product_stock' => 0,
                'product_image' =>'https://img.overclockers.co.uk/images/HS-03M-NC/05e4e38b81d0351597f55b71637a424c.jpg'
            ],
            [
                'product_name' => 'NZXT H710 Case',
                'product_model' => 'H710 Matte Black',
                'product_part' => 'PC case',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 200,
                'product_tagline'=> 'Well-ventilated and well-built PC case with sleek design.',
                'product_description'=> 'This case has exceptional cpu cooling, with its PSU shroud perforated on the side and bottom, large radiator support, high performance airflow, pre-installed fans and seamless cable management.',
                'product_createdate' =>now(),
                'product_stock' => 13,
                'product_image' =>'https://nzxt.com/cdn/shop/files/h7-emea-hero-2000x2000.png?v=1762528364.'
            ],
            [
                'product_name' => 'Corsair 2x120mm Case Fans',
                'product_model' => 'AF120',
                'category_id' => 1,
                'product_part' => 'Cooling Fan',
                'product_colour' => 'Black',
                'product_price' => 50,
                'product_tagline'=> 'High-performance case fans to keep your system cool under load.',
                'product_description'=> 'With 4.38mm-H2O of static pressure, these fans are great for pushing air through obstructions such as high-density radiators. It is Incredibly strong and durable, reinforced with glass fiber, resulting in excellent rigidity, reduced blade vibration, and increased performance. ',
                'product_createdate' =>now(),
                'product_stock' => 10,
                'product_image' =>'https://m.media-amazon.com/images/I/71Pgp9awWGL.jpg'
            ],
            [
                'product_name' => 'Intel Wi-Fi 6 Card',
                'product_model' => 'AX200',
                'category_id' => 1,
                'product_part' => 'NIC',
                'product_colour' => 'White',
                'product_price' => 40,
                'product_tagline'=> 'Next-generation Wi-Fi 6 network card for faster wireless connectivity.',
                'product_description'=> 'Intel\'s Wi-Fi 6 technology, also known as 802.11ax, is designed to provide faster speeds, better performance in crowded environments, and improved power efficiency. It supports dual-stream Wi-Fi in the 2.4GHz, 5GHz, and 6GHz bands, and includes improved TCP throughput',
                'product_createdate' =>now(),
                'product_stock' => 4,
                'product_image' =>'https://m.media-amazon.com/images/I/71Hu6-rhsLL.jpg'
            ],
            [
                'product_name' => 'Samsung 27" Curved Monitor',
                'product_model' => 'Odyssey G5',
                'category_id' => 1,
                'product_price' => 300,
                'product_part' => 'NIC',
                'product_colour' => 'Black',
                'product_tagline'=> 'A curved display with smooth refresh for gaming and productivity.',
                'product_description'=> 'The Samsung 27" Curved Monitor Odyssey G5 offers an incredibly immersive gaming experience with its deep 1000R curve, sharp QHD resolution, and smooth 165Hz refresh rate. It is designed to pull you directly into the action with stunning visuals and rapid performance.',
                'product_createdate' =>now(),
                'product_stock' => 8,
                'product_image' =>'https://m.media-amazon.com/images/I/61VO4NO1vHL._AC_UF1000,1000_QL80_.jpg'
            ],

            [
                'product_name' => 'HyperX Gaming Rig',
                'product_model' => 'HX-5000',
                'product_part' => 'N/A',
                'product_colour' => 'Blue',
                'category_id' => 2,
                'product_price' => 1500,
                'product_tagline' => 'High-end gaming PC with RTX 4070 and Intel i7 processor.',
                'product_description'=> 'Unleash the full potential of your gameplay with the HyperX HX-5000 Sentinel. Engineered for professional-grade performance and uncompromising aesthetics, this rig combines cutting-edge internal hardware with HyperX\'s signature focus on comfort and style.',
                'product_createdate' => now(),
                'product_stock' => 9,
                'product_image' => 'https://m.media-amazon.com/images/I/91QNSIAZLKL._AC_UL480_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Nova Workstation',
                'product_model' => 'NV-3000',
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'category_id' => 2,
                'product_price' => 1300,
                'product_tagline' => 'Reliable PC for creators and multitasking with AMD Ryzen 9.',
                'product_description'=> 'The Nova Pro-Series Workstation is designed for demanding professional tasks, offering performance and reliability. It utilises enterprise-grade components for seamless multitasking and data processing, suitable for continuous operation.',
                'product_createdate' => now(),
                'product_stock' => 3,
                'product_image' => 'https://m.media-amazon.com/images/I/81KnlVQl3bL._AC_SY300_SX300_QL70_ML2_.jpg',
            ],
            [
                'product_name' => 'Stealth Mini-PC',
                'product_model' => 'ST-100',
                'category_id' => 2,
                'product_part' => 'N/A',
                'product_colour' => 'Green',
                'product_price' => 1000,
                'product_tagline' => 'Compact gaming PC with GTX 1660 Ti, perfect for small spaces.',
                'product_description'=> 'The Stealth ST-100 is an ultra-compact, fanless industrial mini PC built for the most challenging environments and AI-driven applications. This system delivers powerful edge computing performance.',
                'product_createdate' => now(),
                'product_stock' => 7,
                'product_image' => 'https://m.media-amazon.com/images/I/81VPFlY3WmL._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Titan Pro Gaming',
                'product_model' => 'TP-700',
                'category_id' => 2,
                'product_price' => 1800,
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'product_tagline' => 'Top-tier gaming experience with RTX 4080 and 32GB RAM.',
                'product_description'=> 'Dominate every battlefield with the Titan Pro Gaming TP-700 desktop PC, a machine forged for peak performance and unparalleled gaming experiences. Featuring cutting-edge hardware and precision engineering, the TP-700 delivers hyper-realistic visuals and lightning-fast speeds for the most demanding gamers and creators.',
                'product_createdate' => now(),
                'product_stock' => 4,
                'product_image' => 'https://m.media-amazon.com/images/I/71JjWbIHvIL._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Eco Budget PC',
                'product_model' => 'EB-250',
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'category_id' => 2,
                'product_price' => 700,
                'product_tagline' => 'Affordable PC for everyday use with integrated graphics.',
                'product_description'=> 'Meet the EB-250, the PC designed for the conscious consumer. Whether you\'re tackling spreadsheets, streaming in HD, or diving into popular game titles like League of Legends or Roblox, this system delivers a smooth experience while keeping your energy bills and environmental impact low.',
                'product_createdate' => now(),
                'product_stock' => 10,
                'product_image' => 'https://m.media-amazon.com/images/I/71uQil+zxJL._AC_UY327_FMwebp_QL65_.jpg',
            ],

            [
                'product_name' => 'Ultimate Gaming Bundle',
                'product_model' => 'UltimateX',
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'category_id' => 3,
                'product_part' => 'N/A',
                'product_price' => 2500,
                'product_tagline' => 'PC + monitor + keyboard + mouse combo for gamers.',
                'product_description'=> 'Featuring the The OcUK Gaming Mach 6, an elite pre-built system designed for 1440p and 4K gaming at high frame rates, with a LENOVO Legion Pro 34WD-10 OLED monitor, and the Logitech G Pro X Series keyboard and mouse for the ultimate gaming experience.',
                'product_createdate' => now(),
                'product_stock' => 10,
                'product_image' => 'https://m.media-amazon.com/images/I/81EFH6sT5CL._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Creator\'s Bundle',
                'product_model' => 'YCREATE',
                'product_part' => 'N/A',
                'product_colour' => 'Blue',
                'category_id' => 3,
                'product_price' => 2200,
                'product_tagline' => 'Workstation PC bundle with dual monitors and professional accessories.',
                'product_description'=> 'Featuring the Nova Pro-Series Studio, with a ASUS ProArt PA32UCG-K monitor, and the Logitech MX Master Series keyboard and mouse to allow for high-intensity rendering and multi-threaded creative workflows.',
                'product_createdate' => now(),
                'product_stock' => 6,
                'product_image' => 'https://m.media-amazon.com/images/I/613+s9cGm5L._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Mini Office Bundle',
                'product_model' => 'WorkX',
                'category_id' => 3,
                'product_part' => 'N/A',
                'product_colour' => 'Black',
                'product_price' => 1200,
                'product_tagline' => 'Compact PC bundle with monitor, keyboard, and mouse for home office.',
                'product_description'=> 'Featuring the Stealth LPC-925 Mini PC, with a Samsung 27" Odyssey G5 monitor and the Logitech MK470 Slim Combo keyboard and mouse. It is designed to reclaim desk space without sacrificing the speed needed for heavy multitasking and video conferencing.',
                'product_createdate' => now(),
                'product_stock' => 9,
                'product_image' => 'https://m.media-amazon.com/images/I/61Owitvq44L._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Streaming Bundle',
                'product_model' => 'StreamMaster',
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'category_id' => 3,
                'product_price' => 1900,
                'product_tagline' => 'PC with webcam, mic, and capture card for live streaming setup.',
                'product_description'=> 'Featuring the Ryzen 5 & GTX 1660 Series PC, with a ASRock 24.5" 144Hz IPS monitor along with some streaming essentials. A 1080p FHD Webcam and a dedicated Tripod Microphone for crisp audio and visuals along with a 1080p HDMI capture card, allowing you to stream your PS5, Xbox, or Switch directly through the PC.',
                'product_createdate' => now(),
                'product_stock' => 12,
                'product_image' => 'https://m.media-amazon.com/images/I/71uITD7P8QL._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'Beginner Gamer Bundle',
                'product_model' => 'StartUp',
                'product_part' => 'N/A',
                'product_colour' => 'RGB',
                'category_id' => 3,
                'product_price' => 1000,
                'product_tagline' => 'Entry-level gaming PC bundle with essential peripherals.',
                'product_description'=> 'Featuring the Vibox V-192 Gaming Rig, with a 23" 1080p Monitor and a 4-in-1 RGB Kit. The Kit Includes a matching LED keyboard, mouse, headset, and mouse mat to complete the "gamer aesthetic" right out of the box.',
                'product_createdate' => now(),
                'product_stock' => 2,
                'product_image' => 'https://m.media-amazon.com/images/I/712zBD3Mj-L._AC_UY327_FMwebp_QL65_.jpg',
            ],
            [
                'product_name' => 'RTX 4070 Super',
                'product_model' => 'RTX4070S',
                'product_part' => 'GPU',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 650,
                'product_tagline'=> 'High-performance GPU ideal for 1440p gaming.',
                'product_description'=> 'A a high-end graphics card that delivers exceptional 4K gaming performance and AI-accelerated creative power using the ultra-efficient Ada Lovelace architecture.',
                'product_createdate' => now(),
                'product_stock' => 10,
                'product_image' => 'https://cdn.wccftech.com/wp-content/uploads/2023/12/ASUS-NVIDIA-GeForce-RTX-4070-SUPER-12-GB-GPU-Dual-Graphics-Card.jpg'
            ],
            [
                'product_name' => 'RX 7900 XT',
                'product_model' => 'RX7900XT',
                'product_part' => 'GPU',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 720,
                'product_tagline'=> 'High-performance AMD flagship GPU for ultra fast gaming.',
                'product_description'=> 'A high-performance graphics card built on the revolutionary RDNA 3 architecture, designed to deliver exceptional 4K gaming and professional application performance.',
                'product_createdate' => now(),
                'product_stock' => 6,
                'product_image' => 'https://www.techpowerup.com/img/6BN8YnL95l0iNZy1.jpg'
            ],
            [
                'product_name' => 'RTX 4060',
                'product_model' => 'RTX4060',
                'product_part' => 'GPU',
                'product_colour' => 'White',
                'category_id' => 1,
                'product_price' => 350,
                'product_tagline'=> 'A great mid-range budget gaming GPU for optimal gaming.',
                'product_description'=> 'A mid-range graphics card designed as a "sweet spot" for high-refresh-rate 1080p gaming. It is highly energy-efficient and leverages the latest AI-accelerated features like DLSS 3 and ray tracing to deliver excellent performance.',
                'product_createdate' => now(),
                'product_stock' => 14,
                'product_image' => 'https://m.media-amazon.com/images/I/719gNHUGR7L._AC_SL1500_.jpg'
            ],
            [
                'product_name'=>'Ryzen 7 7800X3D',
                'product_model'=>'7800X3D',
                'product_part'=>'CPU',
                'product_colour'=>'Silver',
                'category_id'=>1,
                'product_price'=>450,
                'product_tagline'=>'A Top gaming CPU developed with 3D V-cache Technology.',
                'product_description'=> 'Widely considered the best gaming processor available, It leverages revolutionary 3D V-Cache technology to deliver unparalleled in-game performance while maintaining high power efficiency. It\'s an 8-core, 16-thread CPU that is "future-ready" on the AM5 platform.',
                'product_createdate'=>now(),
                'product_stock'=>8,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/f0e0e59d75066ec825667b71c31e3c83.256p.jpg'
            ],
            [
                'product_name'=>'Intel i7 14700K',
                'product_model'=>'i7-14700K',
                'product_part'=>'CPU',
                'product_colour'=>'Silver',
                'category_id'=>1,
                'product_price'=>420,
                'product_tagline'=>'A high-end Intel CPU for both gaming and multitasking.',
                'product_description'=> 'An Incredible 14th Generation desktop processor that excels in both high-end gaming and multi-threaded productivity tasks, thanks to its hybrid architecture featuring 20 cores (8 performance-cores and 12 efficient-cores).',
                'product_createdate'=>now(),
                'product_stock'=>9,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/c3e5d01cec2fa20b6f47fe8a400c08d6.256p.jpg'
            ],
            [
                'product_name'=>'Ryzen 5 7600X',
                'product_model'=>'7600X',
                'product_part'=>'CPU',
                'product_colour'=>'Silver',
                'category_id'=>1,
                'product_price'=>260,
                'product_tagline'=>'Excellent mid-range CPU with a high performance.',
                'product_description'=>'A high-value, performance-focused 6-core processor designed to be the foundation of an excellent mid-range gaming PC. It offers strong single-threaded performance thanks to the Zen 4 architecture and utilizes the new AM5 platform, ensuring a long upgrade path.',
                'product_createdate'=>now(),
                'product_stock'=>11,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/fd6305088c9d16d59017b380fb9c408a.256p.jpg'
            ],

            [
                'product_name'=>'Kingston Fury 16GB DDR5',
                'product_model'=>'KF16',
                'product_part'=>'RAM',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>90,
                'product_tagline'=>'Fast DDR5 RAM kit with enhanced stability.',
                'product_description'=> 'Offers cutting-edge technology for next-generation gaming and productivity platforms, with key features including high speeds, on-die ECC for stability, and flexible overclocking options.',
                'product_createdate'=>now(),
                'product_stock'=>20,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/547d30a3ba49dc763a8c23b28f7ac74b.256p.jpg'
            ],
            [
                'product_name'=>'G.Skill Trident Z 32GB',
                'product_model'=>'TZ32',
                'product_part'=>'RAM',
                'product_colour'=>'RGB',
                'category_id'=>1,
                'product_price'=>180,
                'product_tagline'=>'RGB high-performance RAM with extreme speed.',
                'product_description'=> 'Offers top-tier performance for enthusiasts, available in the Trident Z5, Z5 Neo, and Z5 Royal series, with speeds ranging from 5600MHz to 8000MHz to suit various high-performance systems.',
                'product_createdate'=>now(),
                'product_stock'=>7,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/67c83cfd051636aaa95e8b00b6e95d6e.256p.jpg'
            ],
            [
                'product_name'=>'Corsair LPX 16GB DDR4',
                'product_model'=>'LPX16',
                'product_part'=>'RAM',
                'product_colour'=>'White',
                'category_id'=>1,
                'product_price'=>65,
                'product_tagline'=>'Reliable DDR4 memory with versatile speeds.',
                'product_description'=> 'An industry standard, high-performance RAM known for its reliability, low-profile design, and excellent overclocking potential. It is one of the most popular choices for building or upgrading a budget-to-mid-range PC system.',
                'product_createdate'=>now(),
                'product_stock'=>18,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/e4bd808b09151a16fbdec0dbf447373a.256p.jpg'
            ],

            [
                'product_name'=>'WD Black SN850X 2TB',
                'product_model'=>'SN850X',
                'product_part'=>'SSD',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>220,
                'product_tagline'=>'Gaming-optimised High-speed NVMe SSD.',
                'product_description'=> 'A high-performance PCIe 4.0 M.2 NVMe SSD designed for elite gaming and intensive creative applications, offering read speeds of up to 7,300 MB/s and compatibility with both PCs and the PS5 console.',
                'product_createdate'=>now(),
                'product_stock'=>9,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/8e6dbae8a0f3c6572216c8758ce5a0b5.256p.jpg'
            ],
            [
                'product_name'=>'Crucial P5 Plus 1TB',
                'product_model'=>'P5P',
                'product_part'=>'SSD',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>110,
                'product_tagline'=>'High-speed Gen4 SSD with versatile compatibility.',
                'product_description'=> 'A high-performance PCIe 4.0 NVMe M.2 SSD from Micron that offers fast read speeds of up to 6,600 MB/s, making it an excellent choice for a mid-to-high-range gaming PC or as a storage expansion for a PlayStation 5 console.',
                'product_createdate'=>now(),
                'product_stock'=>13,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/8e6dbae8a0f3c6572216c8758ce5a0b5.256p.jpg'
            ],
            [
                'product_name'=>'Samsung 990 Pro 1TB',
                'product_model'=>'990Pro',
                'product_part'=>'SSD',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>140,
                'product_tagline'=>'Premium SSD performance with optimised thermal control.',
                'product_description'=> 'A flagship PCIe 4.0 NVMe M.2 SSD that provides exceptional performance for high-end gaming and demanding creative workloads, offering read speeds of up to 7,450 MB/s.',
                'product_createdate'=>now(),
                'product_stock'=>10,
                'product_image'=>'https://m.media-amazon.com/images/I/41IWzc1mUwL.jpg'
            ],

            [
                'product_name'=>'Corsair RM850x',
                'product_model'=>'RM850x',
                'product_part'=>'PSU',
                'product_colour'=>'White',
                'category_id'=>1,
                'product_price'=>150,
                'product_tagline'=>'Reliable 850W PSU with fully modular cables.',
                'product_description'=> 'A highly-regarded, fully modular 850W power supply unit known for its quiet operation, high efficiency, and reliable performance in high-end PC builds.',
                'product_createdate'=>now(),
                'product_stock'=>6,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/1752baa3ddb162df098cf33b0b6eeae3.256p.jpg'
            ],
            [
                'product_name'=>'EVGA 750 G6',
                'product_model'=>'SuperNOVA 750G6',
                'product_part'=>'PSU',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>130,
                'product_tagline'=>'Efficient modular PSU with a quiet operation.',
                'product_description'=> 'A high-performance, fully modular 750W power supply renowned for its excellent build quality, high efficiency, and compact size, making it a reliable choice for gaming PCs and high-end systems.',
                'product_createdate'=>now(),
                'product_stock'=>7,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/98319aee12de75fdef0a2b74b918ddf5.256p.jpg'
            ],
            [
                'product_name'=>'Seasonic Focus 650W',
                'product_model'=>'Focus650',
                'product_part'=>'PSU',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>100,
                'product_tagline'=>'Quiet gold-rated PSU with a compact size.',
                'product_description'=> 'A highly-rated power supply unit known for its excellent build quality, high 80 PLUS Gold efficiency, and quiet operation, backed by a robust warranty.',
                'product_createdate'=>now(),
                'product_stock'=>12,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/332544e0e8da6848b9fa83947101de60.256p.jpg'
            ],
            [
                'product_name' => 'MSI B650 Gaming Plus',
                'product_model' => 'B650-GP',
                'product_part' => 'Motherboard',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 180,
                'product_tagline'=> 'AM5 motherboard with PCIe 4.0 and WiFi support.',
                'product_description'=> 'An excellent value ATX motherboard for AMD\'s AM5 platform, offering robust power delivery, high-speed connectivity, and modern features like DDR5 and PCIe 4.0 support for building a future-proof gaming PC.',
                'product_createdate'=>now(),
                'product_stock'=>8,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/ff33ebb87ed9f5fa5f9c54d6d316ae82.256p.jpg'
            ],
            [
                'product_name' => 'ASUS Prime Z790-P',
                'product_model' => 'Z790-P',
                'product_part' => 'Motherboard',
                'product_colour' => 'Black',
                'category_id' => 1,
                'product_price' => 210,
                'product_tagline'=> 'Intel LGA1700 board with DDR5 support.',
                'product_description'=> 'An ATX motherboard designed to unleash the full potential of Intel 14th, 13th, and 12th Gen Core processors on the LGA 1700 socket, offering robust power delivery, comprehensive cooling, and modern connectivity options.',
                'product_createdate'=>now(),
                'product_stock'=>6,
                'product_image'=>'https://m.media-amazon.com/images/I/81Yy8CPeVEL._AC_SX679_.jpg'
            ],
            [
                'product_name'=>'Lian Li Lancool 216',
                'product_model'=>'LANCOOL 216RC-X',
                'product_part'=>'PC Case',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>95,
                'product_tagline'=>'High airflow ATX PC case with tempered glass.',
                'product_description'=> 'A highly popular mid-tower ATX PC case known for its exceptional airflow characteristics, premium build quality, spacious interior, and user-friendly features, making it a top choice for modern gaming builds with large components. ',
                'product_createdate'=>now(),
                'product_stock'=>10,
                'product_image'=>'https://m.media-amazon.com/images/I/41X6Ocd7P5L.jpg'
            ],
            [
                'product_name'=>'Fractal Design Pop Air',
                'product_model'=>'PopAir',
                'product_part'=>'PC Case',
                'product_colour'=>'Black',
                'category_id'=>1,
                'product_price'=>90,
                'product_tagline'=>'Clean design with great airflow performance.',
                'product_description' => 'A popular mid-tower PC case that combines a sleek Scandinavian aesthetic with a focus on high airflow performance, making it a great value option for building a modern gaming PC.',
                'product_createdate'=>now(),
                'product_stock'=>9,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/048e9d2f829061df55885fb8eabd5952.256p.jpg'
            ],
            [
                'product_name'=>'Windows 11 Home',
                'product_model'=>'Win11-H',
                'product_part'=>'Operating System',
                'product_colour'=>'N/A',
                'category_id'=>1,
                'product_price'=>120,
                'product_tagline'=>'The Standard OS, best for everyday users and students.',
                'product_description'=> 'The definitive choice for the modern household, seamlessly blending an intuitive, refined interface with industry-leading gaming technology. Designed for accessibility and speed, it provides a secure environment for everything from creative projects to high-fidelity 4K gaming.',
                'product_createdate'=>now(),
                'product_stock'=>50,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/ed2349ecd618439a2aa96364e9445138.256p.jpg'
            ],
            [
                'product_name'=>'Windows 11 Pro',
                'product_model'=>'Win11-P',
                'product_part'=>'Operating System',
                'product_colour'=>'N/A',
                'category_id'=>1,
                'product_price'=>180,
                'product_tagline'=>'Best for business owners and hardware lovers.',
                'product_description'=> 'Engineered for professionals who demand granular control, enhanced security, and sophisticated management tools. It offers the same polished experience as the Home edition but adds the critical infrastructure required for remote work, data encryption, and virtualisation.',
                'product_createdate'=>now(),
                'product_stock'=>40,
                'product_image'=>'https://cdna.pcpartpicker.com/static/forever/images/product/78f43eb1b5266ea1ad87edc95cb23ba1.256p.jpg'
            ],
            [
                'product_name'=>'Ubuntu Linux Mint USB',
                'product_model'=>'LINUX MINT 20.1',
                'product_part'=>'Operating System',
                'product_colour'=>'N/A',
                'category_id'=>1,
                'product_price'=>1000,
                'product_tagline'=>'Best for developers and those who love linux.',
                'product_description'=> 'Ubuntu stands as the global leader in open-source computing, offering a rock-solid, secure, and highly customisable environment. It is the preferred choice for software engineers and those seeking a high-performance alternative to proprietary ecosystems, providing a seamless bridge between local development and cloud infrastructure.',
                'product_createdate'=>now(),
                'product_stock'=>4,
                'product_image'=>'https://m.media-amazon.com/images/I/61MY8X-U9ZL._AC_SY300_SX300_QL70_ML2_.jpg'
            ],
            [
                'product_name'=>'ArchNode X1 OLED',
                'product_model'=>'ARCH-USB-64GB',
                'product_part'=>'Operating System',
                'product_colour'=>'N/A',
                'category_id'=>1,
                'product_price'=>10,
                'product_tagline'=>'Best for those who seek the ultimate desktop experience.',
                'product_description'=> 'The definitive standard for those who believe an operating system should be built, not just installed. It offers a minimalist "rolling release" model, providing the latest software as soon as it\'s available. This is the unrivalled desktop experience for the architect who demands absolute system transparency and total ownership.',
                'product_createdate'=>now(),
                'product_stock'=>25,
                'product_image'=>'https://i.postimg.cc/0yKsVC9B/archusbnew.png'
            ]
        ]);
    }
}
